####PARA HACER TODOS ESTOS TESTS SE NECESITA LA EXTENSION REST CLIENT!!!
### LOGIN CLIENT
#(de los logins es que sacamos los tokens para hacer los test)
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "cliente@ladralab.com",
  "password": "password"
}

### LOGIN STAFF
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "staff@ladralab.com",
  "password": "password"
}

### LOGIN ADMIN
POST http://127.0.0.1:8000/api/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "admin@ladralab.com",
  "password": "password"
}

### CLIENT -> STAFF (403) (si el cliente intenta entrar como staff, no se le permite)
GET http://127.0.0.1:8000/api/staff/pets
Accept: application/json
#(token de client)
Authorization: Bearer 1|dURZ7tX6hV5PFlNRNIdYTfq2zxl4H6yAbIyGyURN685c61e0 

### STAFF -> STAFF
GET http://127.0.0.1:8000/api/staff/pets
Accept: application/json
#(token de staff)
Authorization: Bearer 2|rJE3p3sSL1wY0CXpLpm3fAZ9po5jcdyVZpsj8QyF5dc74248

### ADMIN -> STAFF
GET http://127.0.0.1:8000/api/staff/pets
Accept: application/json
#(token de admin)
Authorization: Bearer 3|xs2LvUMYBZC6gA4BGFgKoktBctxbagzcIsv3VBkR526ae683

### CLIENT PETS
GET http://127.0.0.1:8000/api/pets
Accept: application/json
#(token de client)
Authorization: Bearer 1|dURZ7tX6hV5PFlNRNIdYTfq2zxl4H6yAbIyGyURN685c61e0

### CLIENT CREATE PET
POST http://127.0.0.1:8000/api/pets
Content-Type: application/json
Accept: application/json
#(token de client)
Authorization: Bearer 1|dURZ7tX6hV5PFlNRNIdYTfq2zxl4H6yAbIyGyURN685c61e0

{
  "name": "Luna",
  "species": "dog",
  "breed": "Beagle",
  "size": "medium",
  "care_notes": "Muy juguetona"
}

### CLIENT RESERVATIONS
GET http://127.0.0.1:8000/api/reservations
Accept: application/json
#(token de client)
Authorization: Bearer 1|dURZ7tX6hV5PFlNRNIdYTfq2zxl4H6yAbIyGyURN685c61e0

### CLIENT CREATE RESERVATION
POST http://127.0.0.1:8000/api/reservations
Content-Type: application/json
Accept: application/json
#(token de client)
Authorization: Bearer 1|dURZ7tX6hV5PFlNRNIdYTfq2zxl4H6yAbIyGyURN685c61e0

{
  "pet_id": 11,
  "service_id": 1,
  "start_at": "2026-05-10 10:00:00",
  "end_at": "2026-05-10 14:00:00",
  "notes": "Primera estancia"
}

### CLIENT CANCEL RESERVATION
PATCH http://127.0.0.1:8000/api/reservations/1/cancel
Accept: application/json
#(token de client)
Authorization: Bearer 1|dURZ7tX6hV5PFlNRNIdYTfq2zxl4H6yAbIyGyURN685c61e0

### CLIENT -> STAFF RESERVATIONS (debe fallar)
GET http://127.0.0.1:8000/api/staff/reservations
Accept: application/json
#(token de client)
Authorization: Bearer 1|dURZ7tX6hV5PFlNRNIdYTfq2zxl4H6yAbIyGyURN685c61e0

### STAFF RESERVATIONS
GET http://127.0.0.1:8000/api/staff/reservations
Accept: application/json
#(token de staff)
Authorization: Bearer 2|rJE3p3sSL1wY0CXpLpm3fAZ9po5jcdyVZpsj8QyF5dc74248

### STAFF UPDATE RESERVATION
PATCH http://127.0.0.1:8000/api/staff/reservations/1
Content-Type: application/json
Accept: application/json
#(token de staff)
Authorization: Bearer 2|rJE3p3sSL1wY0CXpLpm3fAZ9po5jcdyVZpsj8QyF5dc74248

{
  "status": "confirmed"
}

### STAFF CREATE RESERVATION
POST http://127.0.0.1:8000/api/staff/reservations
Content-Type: application/json
Accept: application/json
#(token de staff)
Authorization: Bearer 2|rJE3p3sSL1wY0CXpLpm3fAZ9po5jcdyVZpsj8QyF5dc74248

{
  "client_user_id": 1,
  "pet_id": 4,
  "service_id": 1,
  "start_at": "2026-05-12 09:00:00",
  "end_at": "2026-05-12 12:00:00",
  "notes": "Reserva creada por recepción"
}

### SERVICES LIST
GET http://127.0.0.1:8000/api/services
Accept: application/json

### SERVICE DETAIL
GET http://127.0.0.1:8000/api/services/1
Accept: application/json

### STAFF RESOURCES
GET http://127.0.0.1:8000/api/resources
Accept: application/json
#(token de staff)
Authorization: Bearer 4|IfMa4YFfZqZA0nSEN06nZUTIrYTLlG2ctf8mfbWA5082224d

### CLIENT -> RESOURCES
GET http://127.0.0.1:8000/api/resources
Accept: application/json
#(token de client) (debe fallar)
Authorization: Bearer 5|BjRsg18GfMWQhAs9513nGM8eGYMghKkd28m8Se329a5b891f

### STAFF CREATE RESOURCE
POST http://127.0.0.1:8000/api/resources
Content-Type: application/json
Accept: application/json
#(token de staff)
Authorization: Bearer 6|z41SZ0NEKVXGqGDnnCi3oJ9zVucKXd1PurJPoIF5c36f7ae5

{
  "name": "Box Norte 1",
  "type": "room",
  "zone": "hotel",
  "size_group": "medium",
  "capacity": 2,
  "status": "active"
}

### STAFF UPDATE RESOURCE
PATCH http://127.0.0.1:8000/api/resources/1
Content-Type: application/json
Accept: application/json
#(token de staff)
Authorization: Bearer 6|z41SZ0NEKVXGqGDnnCi3oJ9zVucKXd1PurJPoIF5c36f7ae5

{
  "status": "cleaning"
}

### STAFF MEDIA LIST
GET http://127.0.0.1:8000/api/daily-reports/1/media
Accept: application/json
#(token de staff)
Authorization: Bearer 8|k9snvcgPQKnuXPta2MsuAnovrFLOlx51AQAtJiH95c7edafb

### STAFF CREATE MEDIA
POST http://127.0.0.1:8000/api/daily-reports/1/media
Content-Type: application/json
Accept: application/json
#(token de staff)
Authorization: Bearer 8|k9snvcgPQKnuXPta2MsuAnovrFLOlx51AQAtJiH95c7edafb

{
  "file_path": "images/dog1.jpg",
  "file_type": "image"
}

### STAFF DELETE MEDIA
DELETE http://127.0.0.1:8000/api/daily-reports/1/media/1
Accept: application/json
#(token de staff)
Authorization: Bearer 8|k9snvcgPQKnuXPta2MsuAnovrFLOlx51AQAtJiH95c7edafb

### CLIENT -> MEDIA (debe fallar)
GET http://127.0.0.1:8000/api/daily-reports/1/media
Accept: application/json
#(token de client)
Authorization: Bearer 7|pvlkv7RALA5FfWEKjP8ZxDpACZvivWAYaYMVwTFp41507012